name: Build and Deploy Docs

on:
  push:
    branches:
      - master
      -
permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build docs
        run: npm run docs:build

      - name: Deploy to docs branch
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          folder: ./docs/.vitepress/dist
          branch: docs


      - name: Set up remote repository
        run: git remote add yimuyangshu git@github.com:yimuyangshu/yimuyangshu.git

      - name: Push to remote repository
        run: |
          git subtree push --prefix docs/.vitepress/dist yimuyangshu master