name: Build and Deploy Docs

on:
  push:
    branches:
      - master
      -
permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build docs
        run: npm run docs:build

      - name: Deploy to docs branch
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          folder: ./docs/.vitepress/dist
          branch: docs

      - name: Clone destination repository
        run: |
          git config --global user.name "yimuyangshu"
          git config --global user.email "yimuyangshu@163.com"
          git clone https://github.com/yimuyangshu/yimuyangshu.git
          cd yimuyangshu
          git checkout master
          cd ..

      - name: Copy dist files to destination repository
        run: cp -a dist/. yimuyangshu/

      - name: Commit and push changes to destination repository
        run: |
          cd yimuyangshu
          git add .
          git commit -m "Update docs"
          git push origin master