name: Build and Deploy Docs

on:
  push:
    branches:
      - docs
permissions:
  contents: write

env:
  SSH_PRIVATE_KEY: ${{ secrets.HOME }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 检出仓库
        uses: actions/checkout@v2

      - name: 部署dist文件夹作为独立分支到docs
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          folder: ./docs/.vitepress/dist
          branch: docs

      - name: Push to master
        run: |
          git remote add origin git@github.com:yimuyangshu/yimuyangshu.git
          git push origin master